# Generated by Django 4.2.22 on 2025-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIcount', models.IntegerField(verbose_name='EI计数')),
                ('EOcount', models.IntegerField(verbose_name='EO计数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计数记录',
                'verbose_name_plural': '计数记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
